apiVersion: 1

datasources:
  - name: Ecosystem Telemetry
    type: influxdb
    access: proxy
    uid: ecosystem
    url: http://influxdb:8086
    database: telmetry
    user: admin
    password: adminadmin
    isDefault: true
    editable: true